- name: Gebruiksklaar maken van devices

- name: Oplossen van problemen bij hardware en software

- name: Installeren, configureren en onderhouden van software

- name: Monteren en configureren van netwerk en infrastructuur

- name: Advies over hardware en software

- name: Ondersteuning en deskundigheidsbevoordering bij overgang naar nieuwe devices

- name: Onderhouden van applicaties

- name: Verbeteren van security